### ISSUE TITLE
¿Qué es una compra?

### ISSUE THREAD

**Issue by carlotiii30** [LuciaAnsino/CompraOnline#7]
Para empezar a desarrollar el problema del usuario #3 necesitamos saber qué es una compra. Una compra incluye:
* Un ticket electrónico, que te dan al realizarla. #8 
* Una serie de alimentos, que son los que has comprado. #9 
* Un registro en la lista electrónica. #10

**Comment by JJ** [comment]
Más que plantear qué es una compra, deberías de plantear el problema principal de #3: 

> Por lo que quiero evitar tener que ir incluyendo cada alimento en la lista mencionada.

Una compra es simplemente el resultado de procesar un ticket electrónico con la lógica de negocio, pero lo fundamental es cómo extraer esa información. Deberías crear los issues que planteen los diferentes problemas que esto conlleva.
